# Generated by Django 5.0.6 on 2024-07-03 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroSalas', models.PositiveIntegerField()),
                ('capacidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andar', models.CharField(max_length=1)),
                ('status', models.BooleanField(default=False)),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='main.sala')),
            ],
        ),
    ]
