# Generated by Django 5.0.6 on 2024-07-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='numeroCadeira',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
