# Generated by Django 5.0.6 on 2024-07-03 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cadeira_numerocadeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadeira', to='main.sala'),
        ),
    ]
